project:
  type: website

website:
  title: "Ferns 2027"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: venue.qmd
        text: Venue
      - href: program.qmd
        text: Program
      - href: registration.qmd
        text: Registration
      - href: travel.qmd
        text: Travel
      - href: contact.qmd
        text: Contact

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false

babelquarto:
  languagelinks: navbar
  languagecodes:
    - name: ja
      text: "日本語"
    - name: en
      text: "English"
  mainlanguage: en
  languages: [ja]

title-ja: "国際シダ会議 2027"
lang: en
