---
title: "The 6th International Pteridological Congress: Transformative Pteridology"
---

**The 6th International Pteridological Congress: *Transformative Pteridology*** will be held in **Yokosuka, Japan from August 3-7, 2027** and bring pteridologists together from around the world to share their latest research and findings on the biology of ferns and lycophytes.
The conference will feature keynote lectures, oral presentations, poster sessions, and field trips to explore the rich diversity of ferns and lycophytes in Japan. 

The conference will also be held in tandem with the **Asian Fern Symposium**.
Registered attendees are welcome to join either or both conferences.

## Tentative Schedule

- July 31 (Sat.) ~ Aug. 2, 2027 (Mon.): Pre-conference field trip (dates tentative)
- Aug. 3 (Tues.): Asian Fern Symposium
- Aug. 4 (Wed.): Local Field Trip
- Aug. 5 (Thurs.): International Pteridological Congress (plenary lectures)
- Aug. 6 (Fri.): International Pteridological Congress (oral and poster sessions)
- Aug. 7 (Sat.): International Pteridological Congress (oral and poster sessions)

More details to be announced soon!